language: node_js
node_js:
  - "10"
before_deploy:
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  repo: lmikoto/lmikoto.github.io
  local_dir: public
  target_branch: master
  fqdn: lmikoto.com
  project_name: blog
  email: lmikoto@outlook.com
  name: lmikoto