name: Deploy To Github Pages
on: [repository_dispatch,workflow_dispatch]
jobs: 
  deploy:
     name: Deploy Hexo Public To Pages 
     runs-on: ubuntu-latest
     env: 
        TZ: Asia/Shanghai
     steps:
        - name: Checkout Repository master branch
          uses: actions/checkout@master
        - name: Setup Node.js 10.x
          uses: actions/setup-node@master
          with:
            node-version: "10.x"
        - name: Setup Hexo Dependencies and Generate Public Files
          env:
            YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          run: |
           npm install
           npm run build
        - name: Deploy
          uses: Cecilapp/GitHub-Pages-deploy@2.0.0
          with:
            GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            EMAIL: lmikoto@outlook.com
            BUILD_DIR: public